In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [2]:
df1 = pd.read_csv(r'../../results/fuel-rates-CDB-CHB.csv', delimiter=',', skiprows=0, low_memory=False)

In [3]:
df1

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0,ServiceDateTime,Unnamed: 0.1,Unnamed: 0.1.1,DateKey,CalendarDate,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate(L/s)
0,0,0,1415,1415,33217,2022-04-01 05:55:38,33217,43687,8760,2022-04-01 00:00:00.000,...,POINT (-72.52602 42.14099),0.000000,0.000000,0.000000,0,0.0,conventional,Gillig conventional,26440.0,0.000000
1,1,1,1591,1591,33219,2022-04-01 06:04:01,33219,43689,8760,2022-04-01 00:00:00.000,...,POINT (-72.54524 42.13793),0.000000,0.000000,0.000000,0 days 00:08:23,503.0,conventional,Gillig conventional,26440.0,0.000566
2,2,2,1592,1592,33218,2022-04-01 06:04:01,33218,41707,8760,2022-04-01 00:00:00.000,...,POINT (-72.54524 42.13793),1.329491,15.313257,0.008457,0 days 00:00:00,0.0,conventional,Gillig conventional,26440.0,0.001251
3,3,3,1646,1646,33220,2022-04-01 06:05:51,33220,41708,8760,2022-04-01 00:00:00.000,...,POINT (-72.54618 42.13219),0.135532,7.138389,0.018026,0 days 00:01:50,110.0,conventional,Gillig conventional,26440.0,0.000867
4,4,4,1656,1656,33221,2022-04-01 06:06:13,33221,41709,8760,2022-04-01 00:00:00.000,...,POINT (-72.54585 42.12965),0.057365,15.106779,0.100611,0 days 00:00:22,22.0,conventional,Gillig conventional,26440.0,0.002177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099395,1099395,1099395,1361526,1361526,1361544,2022-04-30 23:54:20,1361544,1325566,8789,2022-04-30 00:00:00.000,...,POINT (-72.53185 42.38201),0.254140,10.517075,0.003673,0 days 00:02:20,140.0,conventional,0,0.0,0.000000
1099396,1099396,1099396,1361530,1361530,1361545,2022-04-30 23:55:24,1361545,1325567,8789,2022-04-30 00:00:00.000,...,POINT (-72.5327 42.375),0.156799,14.194300,0.015960,0 days 00:01:04,64.0,conventional,0,0.0,0.000000
1099397,1099397,1099397,1361539,1361539,1361546,2022-04-30 23:56:47,1361546,1325568,8789,2022-04-30 00:00:00.000,...,POINT (-72.53357 42.36864),0.144950,10.117888,-0.013643,0 days 00:01:23,83.0,conventional,0,0.0,0.000000
1099398,1099398,1099398,1361541,1361541,1361547,2022-04-30 23:57:32,1361547,1325569,8789,2022-04-30 00:00:00.000,...,POINT (-72.53556 42.3656),0.151259,19.474153,0.057755,0 days 00:00:45,45.0,conventional,0,0.0,0.000000
1099399,1099399,1099399,1361546,1361546,1361548,2022-04-30 23:59:29,1361548,1325570,8789,2022-04-30 00:00:00.000,...,POINT (-72.54673 42.35999),0.780486,38.648220,0.045523,0 days 00:01:57,117.0,conventional,0,0.0,0.000000

In [4]:
df1.loc[df1['FuelRate(L/s)']>=10]

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0,ServiceDateTime,Unnamed: 0.1,Unnamed: 0.1.1,DateKey,CalendarDate,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate(L/s)
2373,2373,2373,518649,518649,35590,2022-04-12 14:53:05,35590,491234,8771,2022-04-12 00:00:00.000,...,POINT (-72.59992 42.11141),0.101070,146.390045,9.794526,0 days 00:00:04,4.0,conventional,Gillig conventional,26440.0,147.542048
3981,3981,3981,921578,921578,37198,2022-04-21 12:29:02,37198,934677,8780,2022-04-21 00:00:00.000,...,POINT (-72.65941 42.10559),0.095352,110.487280,5.413311,0 days 00:00:05,5.0,conventional,Gillig conventional,26440.0,26.635126
36996,36996,36996,1057434,1057434,70213,2022-04-25 06:03:34,70213,1090550,8784,2022-04-25 00:00:00.000,...,POINT (-72.65941 42.10559),0.095352,138.109100,3.248175,0 days 00:00:04,4.0,conventional,Gillig conventional,26440.0,15.572642
43363,43363,43363,542421,542421,76579,2022-04-13 06:30:42,76579,544429,8772,2022-04-13 00:00:00.000,...,POINT (-72.5946 42.10657),0.013400,77.633874,19.041603,0 days 00:00:00,0.0,conventional,Gillig conventional,26440.0,159.458489
62251,62251,62251,480687,480687,95468,2022-04-11 19:15:03,95468,441082,8770,2022-04-11 00:00:00.000,...,POINT (-72.59263 42.10368),0.058001,84.008947,5.252478,0 days 00:00:04,4.0,conventional,Gillig conventional,26440.0,14.265689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
894167,894167,894167,527322,527322,927384,2022-04-12 17:15:35,927384,501633,8771,2022-04-12 00:00:00.000,...,POINT (-72.56204 42.11211),0.080534,116.645371,3.911087,0 days 00:00:04,4.0,conventional,New Flyer 40 conventional,26000.0,18.437975
895397,895397,895397,624943,624943,928614,2022-04-14 14:51:54,928614,603519,8773,2022-04-14 00:00:00.000,...,POINT (-72.56069 42.12283),0.064366,93.228175,5.481592,0 days 00:00:04,4.0,conventional,New Flyer 40 conventional,26000.0,21.915714
922093,922093,922093,1199160,1199160,955309,2022-04-27 16:36:46,955309,1164656,8786,2022-04-27 00:00:00.000,...,POINT (-72.59471 42.10589),0.011762,68.145966,18.929482,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,154.851847
933110,933110,933110,788188,788188,966327,2022-04-18 17:14:32,966327,766563,8777,2022-04-18 00:00:00.000,...,POINT (-72.56204 42.11211),0.080534,116.645371,3.808986,0 days 00:00:04,4.0,conventional,New Flyer 40 conventional,26000.0,18.852667
936134,936134,936134,998238,998238,969351,2022-04-22 20:30:33,969351,955075,8781,2022-04-22 00:00:00.000,...,POINT (-72.59512 42.10592),0.016629,96.340564,26.434911,0 days 00:00:01,1.0,conventional,New Flyer 40 conventional,26000.0,666.434287

In [ ]:
figure(figsize=(14, 9.5), dpi=400)
plt.plot_date(x=df1['ServiceDateTime']  , y=df1['FuelRate(L/s)'], fmt='o', tz=None, xdate=True, ydate=False, color='teal')
plt.ylabel("FuelRate(L/s)", fontsize=36)
plt.xticks(fontsize=28, rotation = 45)
plt.yticks(fontsize=28)
plt.savefig(r'../../figures/FuelRate-CDB-CHB.png', dpi=400, bbox_inches='tight')
plt.show()

In [ ]:
df_filtered=df1.loc[df1['FuelRate(L/s)']<=10]

In [ ]:
figure(figsize=(14, 9.5), dpi=400)
plt.plot_date(x=df_filtered['ServiceDateTime']  , y=df_filtered['FuelRate(L/s)'], fmt='o', tz=None, xdate=True, ydate=False, color='teal')
plt.ylabel("FuelRate(L/s)", fontsize=36)
plt.xticks(fontsize=28, rotation = 45)
plt.yticks(fontsize=28)
plt.savefig(r'../../figures/FuelRate-filtered-CDB-CHB.png', dpi=400, bbox_inches='tight')
plt.show()

In [ ]:
df1['FuelRate(L/s)'].hist()

In [16]:
df1['FuelRate(L/s)'].median()

0.0006396186765981

In [19]:
#df1.columns
df1['Vehicle'].unique()

array([3303, 7901, 3317, 3322, 7815, 3401, 3319, 3402, 3312, 1567, 1824,
       1843, 1655, 1659, 1672, 1850, 1640, 1648, 1857, 1822, 1619, 1823,
       1714, 1849, 1723, 7551, 1814, 1844, 1670, 1712, 1574, 1410, 1553,
       7811, 1577, 1716, 1552, 1722, 1557, 1710, 1711, 7660, 1821, 1861,
       1803, 1817, 1720, 1858, 1836, 1854, 1715, 1653, 1855, 1804, 1856,
       1643, 1657, 1578, 1812, 1671, 1575, 1555, 1815, 1654, 3302, 5574,
       1860, 1568, 1811, 1642, 1660, 1649, 1650, 3323, 1566, 1721, 1837,
       1662, 7661, 7813, 1801, 7814, 3307, 1564, 1663, 3318, 3313, 7554,
       1644, 3222, 3311, 3310, 7553, 3305, 1728, 3225, 3308, 7802, 3301,
       1563, 3501, 1835, 1572, 1848, 3226, 1658, 7801, 1652, 1805, 1727,
       1841, 7816, 7552, 1725, 7662, 1853, 7812, 1717, 1842, 1845, 3316,
       3321, 1656, 1852, 1847, 1726, 1813, 1859, 1802, 1205, 3223, 3320,
       7610, 1565, 1576, 3306, 7550, 1834, 1729, 1851, 1833, 1826, 1701,
       3324, 3212, 1411, 3309, 1819, 7902, 1661, 1412, 3228, 1571],
      dtype=int64)