In [1]:
import pandas as pd

In [2]:
df_final = pd.read_csv(r'../../results/computed-fuel-rates.csv', delimiter=',', skiprows=0, low_memory=False)

In [3]:
df_final.columns

Index(['Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'ServiceDateTime',
       'Unnamed: 0', 'Unnamed: 0.1', 'DateKey', 'CalendarDate', 'Year',
       'Month', 'OpKey', 'Operator', 'RtKey', 'RtKey2', 'Route', 'RouteName',
       'TripKey', 'Trip', 'StopKey', 'Stop', 'StopName', 'Lat', 'Lon',
       'Vehicle', 'VehicleType', 'SeatedCap', 'TotalCap', 'Boards', 'Alights',
       'Onboard', 'Bike', 'Wheelchair', 'Weekday', 'Hour', 'Minute', 'Second',
       'Date', 'Daytype', 'time', 'geometry', 'dist', 'Speed', 'Acceleration',
       'time_delta', 'time_delta_in_seconds', 'Powertrain', 'VehicleModel',
       'Vehicle_mass', 'FuelRate/Energy'],
      dtype='object')

In [4]:
df_final.Vehicle_mass

0         26900.0
1         26900.0
2         26900.0
3         26900.0
4         26900.0
           ...
901906    26000.0
901907    26000.0
901908    26000.0
901909    26000.0
901910    26000.0
Name: Vehicle_mass, Length: 901911, dtype: float64

In [5]:
zeros = df_final[df_final['FuelRate/Energy'] == 0]
zeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate/Energy
2391,1297419,1297419,2391,2022-04-29 14:01:44,2391,1273034,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.52602 42.14098),0.000000,0.000000,0.000000,0,0.0,electric,2021 NEW FLYER XE35 (ELECTRIC),26900.0,0.0
2393,1299039,1299039,2393,2022-04-29 14:28:20,2393,1273500,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.65278 42.19514),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE35 (ELECTRIC),26900.0,0.0
2405,1300534,1300534,2406,2022-04-29 14:47:14,2406,1273512,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.5948 42.1062),0.000000,0.000000,0.000000,0 days 00:05:35,335.0,electric,2021 NEW FLYER XE35 (ELECTRIC),26900.0,0.0
2406,1300535,1300535,2405,2022-04-29 14:47:14,2405,1273068,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.5948 42.1062),1.572999,27.204073,-0.037508,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE35 (ELECTRIC),26900.0,0.0
2411,1305198,1305198,2411,2022-04-29 16:00:28,2411,1312240,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.54524 42.13792),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE35 (ELECTRIC),26900.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33160,1318227,1318227,33160,2022-04-29 19:39:59,33160,1301298,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.60757 42.20822),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE40 (ELECTRIC),32770.0,0.0
33181,1319316,1319316,33182,2022-04-29 20:06:00,33182,1301411,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.64057 42.16926),0.000000,0.000000,0.000000,0 days 00:03:25,205.0,electric,2021 NEW FLYER XE40 (ELECTRIC),32770.0,0.0
33182,1319317,1319317,33181,2022-04-29 20:06:00,33181,1301319,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.64057 42.16926),0.070990,2.006278,-0.010318,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE40 (ELECTRIC),32770.0,0.0
33215,1320030,1320030,33216,2022-04-29 20:27:55,33216,1301444,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.59471 42.10589),0.000000,0.000000,0.000000,0 days 00:03:02,182.0,electric,2021 NEW FLYER XE40 (ELECTRIC),32770.0,0.0
33216,1320031,1320031,33215,2022-04-29 20:27:55,33215,1273215,8788,2022-04-29 00:00:00.000,2022,4,...,POINT (-72.59471 42.10589),0.269665,8.584260,-0.052852,0 days 00:00:00,0.0,electric,2021 NEW FLYER XE40 (ELECTRIC),32770.0,0.0

In [6]:
df_final.sort_values(by=['Vehicle','ServiceDateTime'], ascending=True, inplace=True)

In [7]:
df_final

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate/Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.001660
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.001660
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.001660
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.253093
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.175366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901906,266987,266987,901906,2022-04-06 21:01:28,901906,237016,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.5815 42.09564),0.064706,20.826816,-0.071679,0 days 00:00:18,18.0,conventional,New Flyer 40 conventional,26000.0,0.021026
901907,266999,266999,901907,2022-04-06 21:01:51,901907,237017,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58221 42.09708),0.057389,14.456214,-0.076940,0 days 00:00:23,23.0,conventional,New Flyer 40 conventional,26000.0,0.004668
901908,267005,267005,901908,2022-04-06 21:02:06,901908,237019,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58359 42.09859),0.100333,38.752688,0.449936,0 days 00:00:15,15.0,conventional,New Flyer 40 conventional,26000.0,1.622388
901909,267031,267031,901909,2022-04-06 21:03:06,901909,237020,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58471 42.09943),0.079310,7.658244,-0.143956,0 days 00:01:00,60.0,conventional,New Flyer 40 conventional,26000.0,0.001660
901910,267058,267058,901910,2022-04-06 21:04:09,901910,237023,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58821 42.10162),0.246030,22.625501,0.065993,0 days 00:01:03,63.0,conventional,New Flyer 40 conventional,26000.0,0.261100

In [8]:
for i in df_final.index:
    if i==0:
        df_final.at[i , 'FuelRate/Energy'] = 0
    elif df_final['Vehicle_mass'].loc[i]==0:
        df_final.at[i , 'FuelRate/Energy'] = 0
    else:
        if df_final['Vehicle'].loc[i]==df_final['Vehicle'].loc[i-1]:
            if df_final['Date'].loc[i]!=df_final['Date'].loc[i-1]:
                df_final.at[i , 'FuelRate/Energy'] = 0
        else:
            df_final.at[i , 'FuelRate/Energy'] = 0

In [9]:
df_final

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate/Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.000000
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.001660
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.001660
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.253093
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.175366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901906,266987,266987,901906,2022-04-06 21:01:28,901906,237016,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.5815 42.09564),0.064706,20.826816,-0.071679,0 days 00:00:18,18.0,conventional,New Flyer 40 conventional,26000.0,0.021026
901907,266999,266999,901907,2022-04-06 21:01:51,901907,237017,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58221 42.09708),0.057389,14.456214,-0.076940,0 days 00:00:23,23.0,conventional,New Flyer 40 conventional,26000.0,0.004668
901908,267005,267005,901908,2022-04-06 21:02:06,901908,237019,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58359 42.09859),0.100333,38.752688,0.449936,0 days 00:00:15,15.0,conventional,New Flyer 40 conventional,26000.0,1.622388
901909,267031,267031,901909,2022-04-06 21:03:06,901909,237020,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58471 42.09943),0.079310,7.658244,-0.143956,0 days 00:01:00,60.0,conventional,New Flyer 40 conventional,26000.0,0.001660
901910,267058,267058,901910,2022-04-06 21:04:09,901910,237023,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58821 42.10162),0.246030,22.625501,0.065993,0 days 00:01:03,63.0,conventional,New Flyer 40 conventional,26000.0,0.261100

In [10]:
zeros = df_final[df_final['FuelRate/Energy'] == 0]
zeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate/Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.0,0.0,0.0,0,0.0,conventional,0,26900.0,0.0
282,166376,166376,282,2022-04-05 06:51:35,282,163151,8764,2022-04-05 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.0,0.0,0.0,0,0.0,conventional,0,26900.0,0.0
563,286405,286405,563,2022-04-07 10:44:48,563,269348,8766,2022-04-07 00:00:00.000,2022,4,...,POINT (-72.62941 42.33355),0.0,0.0,0.0,0,0.0,conventional,0,26900.0,0.0
777,543357,543357,777,2022-04-13 06:47:15,777,543606,8772,2022-04-13 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.0,0.0,0.0,0,0.0,conventional,0,26900.0,0.0
1058,852499,852499,1058,2022-04-20 06:41:10,1058,853355,8779,2022-04-20 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.0,0.0,0.0,0,0.0,conventional,0,26900.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
898716,1827,1827,898716,2022-04-01 06:11:16,898716,43540,8760,2022-04-01 00:00:00.000,2022,4,...,POINT (-72.52602 42.14099),0.0,0.0,0.0,0,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
899162,71683,71683,899162,2022-04-02 13:32:35,899162,67073,8761,2022-04-02 00:00:00.000,2022,4,...,POINT (-72.59227 42.10334),0.0,0.0,0.0,0,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
899703,112110,112110,899703,2022-04-04 06:45:03,899703,152290,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.60545 42.11355),0.0,0.0,0.0,0,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
900261,163319,163319,900261,2022-04-05 05:06:00,900261,206320,8764,2022-04-05 00:00:00.000,2022,4,...,POINT (-72.52602 42.14099),0.0,0.0,0.0,0,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
900928,217550,217550,900928,2022-04-06 06:01:57,900928,231271,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.59456 42.10602),0.0,0.0,0.0,0,0.0,conventional,New Flyer 40 conventional,26000.0,0.0

In [11]:
nonzeros = df_final[df_final['FuelRate/Energy'] != 0]
nonzeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,FuelRate/Energy
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.001660
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.001660
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.253093
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.175366
5,112735,112735,5,2022-04-04 06:55:38,5,109329,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62412 42.32895),0.253127,22.561887,-0.006965,0 days 00:01:05,65.0,conventional,0,26900.0,0.136266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
901906,266987,266987,901906,2022-04-06 21:01:28,901906,237016,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.5815 42.09564),0.064706,20.826816,-0.071679,0 days 00:00:18,18.0,conventional,New Flyer 40 conventional,26000.0,0.021026
901907,266999,266999,901907,2022-04-06 21:01:51,901907,237017,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58221 42.09708),0.057389,14.456214,-0.076940,0 days 00:00:23,23.0,conventional,New Flyer 40 conventional,26000.0,0.004668
901908,267005,267005,901908,2022-04-06 21:02:06,901908,237019,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58359 42.09859),0.100333,38.752688,0.449936,0 days 00:00:15,15.0,conventional,New Flyer 40 conventional,26000.0,1.622388
901909,267031,267031,901909,2022-04-06 21:03:06,901909,237020,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58471 42.09943),0.079310,7.658244,-0.143956,0 days 00:01:00,60.0,conventional,New Flyer 40 conventional,26000.0,0.001660
901910,267058,267058,901910,2022-04-06 21:04:09,901910,237023,8765,2022-04-06 00:00:00.000,2022,4,...,POINT (-72.58821 42.10162),0.246030,22.625501,0.065993,0 days 00:01:03,63.0,conventional,New Flyer 40 conventional,26000.0,0.261100

In [12]:
df_final.to_csv(r'../../results/computed-fuel-rates.csv')

In [13]:
df_final['FuelRate/Energy']

0         0.000000
1         0.001660
2         0.001660
3         0.253093
4         0.175366
            ...
901906    0.021026
901907    0.004668
901908    1.622388
901909    0.001660
901910    0.261100
Name: FuelRate/Energy, Length: 901911, dtype: float64

In [14]:
df_final['FuelRate/Energy'].dtypes

dtype('float64')