In [15]:
import pandas as pd

In [16]:
df_final = pd.read_csv(r'../../results/computed-fuel-rates.csv', delimiter=',', skiprows=0, low_memory=False)

In [17]:
df_final.columns

Index(['Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'ServiceDateTime',
       'Unnamed: 0', 'Unnamed: 0.1', 'DateKey', 'CalendarDate', 'Year',
       'Month', 'OpKey', 'Operator', 'RtKey', 'RtKey2', 'Route', 'RouteName',
       'TripKey', 'Trip', 'StopKey', 'Stop', 'StopName', 'Lat', 'Lon',
       'Vehicle', 'VehicleType', 'SeatedCap', 'TotalCap', 'Boards', 'Alights',
       'Onboard', 'Bike', 'Wheelchair', 'Weekday', 'Hour', 'Minute', 'Second',
       'Date', 'Daytype', 'time', 'geometry', 'dist', 'Speed', 'Acceleration',
       'time_delta', 'time_delta_in_seconds', 'Powertrain', 'VehicleModel',
       'Vehicle_mass', 'Energy'],
      dtype='object')

In [18]:
df_final.Vehicle_mass

0         26900.0
1         26900.0
2         26900.0
3         26900.0
4         26900.0
           ...
837342    26000.0
837343    26000.0
837344    26000.0
837345    26000.0
837346    26000.0
Name: Vehicle_mass, Length: 837347, dtype: float64

In [20]:
zeros = df_final[df_final['Energy'] == 0]
zeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.0
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.0
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.0
16,114379,114379,16,2022-04-04 07:20:47,16,109340,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.57411 42.25425),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.0
32,116181,116181,33,2022-04-04 07:52:30,33,109357,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:09:45,585.0,conventional,0,26900.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837214,1003265,1003265,837215,2022-04-23 07:00:39,837215,1012774,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.59458 42.10609),0.000000,0.000000,0.000000,0 days 00:09:53,593.0,conventional,New Flyer 40 conventional,26000.0,0.0
837215,1003266,1003266,837214,2022-04-23 07:00:39,837214,1012731,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.59458 42.10609),0.143646,1.403421,-0.006186,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
837254,1003916,1003916,837254,2022-04-23 07:24:22,837254,1012874,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.57859 42.17426),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
837329,1005901,1005901,837330,2022-04-23 08:20:51,837330,1012994,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.50799 42.08599),0.000000,0.000000,0.000000,0 days 00:01:10,70.0,conventional,New Flyer 40 conventional,26000.0,0.0
837330,1005902,1005902,837329,2022-04-23 08:20:51,837329,1012993,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.50799 42.08599),0.219882,18.198768,0.041536,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0

In [21]:
df_final.sort_values(by=['Vehicle','ServiceDateTime'], ascending=True, inplace=True)

In [22]:
df_final

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.000000
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.000000
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.000000
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.635820
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.521954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837342,1006217,1006217,837342,2022-04-23 08:30:25,837342,1013006,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52768 42.09206),0.063676,52.701729,-0.148894,0 days 00:00:07,7.0,conventional,New Flyer 40 conventional,26000.0,-0.024423
837343,1006225,1006225,837343,2022-04-23 08:30:37,837343,1013007,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52919 42.09177),0.104504,50.454912,-0.052010,0 days 00:00:12,12.0,conventional,New Flyer 40 conventional,26000.0,0.034416
837344,1006253,1006253,837344,2022-04-23 08:31:14,837344,1013008,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53309 42.09103),0.269901,42.262309,-0.061506,0 days 00:00:37,37.0,conventional,New Flyer 40 conventional,26000.0,0.070101
837345,1006262,1006262,837345,2022-04-23 08:31:36,837345,1013009,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53664 42.09038),0.245652,64.691529,0.283198,0 days 00:00:22,22.0,conventional,New Flyer 40 conventional,26000.0,1.293329
837346,1006269,1006269,837346,2022-04-23 08:31:49,837346,1013010,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53886 42.08995),0.153646,68.474515,0.080833,0 days 00:00:13,13.0,conventional,New Flyer 40 conventional,26000.0,0.413014

In [23]:
for i in df_final.index:
    if i==0:
        df_final.at[i , 'Energy'] = 0
    elif df_final['Vehicle_mass'].loc[i]==0:
        df_final.at[i , 'Energy'] = 0
    else:
        if df_final['Vehicle'].loc[i]==df_final['Vehicle'].loc[i-1]:
            if df_final['Date'].loc[i]!=df_final['Date'].loc[i-1]:
                df_final.at[i , 'Energy'] = 0
        else:
            df_final.at[i , 'Energy'] = 0

In [24]:
df_final

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.000000
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.000000
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.000000
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.635820
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.521954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837342,1006217,1006217,837342,2022-04-23 08:30:25,837342,1013006,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52768 42.09206),0.063676,52.701729,-0.148894,0 days 00:00:07,7.0,conventional,New Flyer 40 conventional,26000.0,-0.024423
837343,1006225,1006225,837343,2022-04-23 08:30:37,837343,1013007,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52919 42.09177),0.104504,50.454912,-0.052010,0 days 00:00:12,12.0,conventional,New Flyer 40 conventional,26000.0,0.034416
837344,1006253,1006253,837344,2022-04-23 08:31:14,837344,1013008,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53309 42.09103),0.269901,42.262309,-0.061506,0 days 00:00:37,37.0,conventional,New Flyer 40 conventional,26000.0,0.070101
837345,1006262,1006262,837345,2022-04-23 08:31:36,837345,1013009,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53664 42.09038),0.245652,64.691529,0.283198,0 days 00:00:22,22.0,conventional,New Flyer 40 conventional,26000.0,1.293329
837346,1006269,1006269,837346,2022-04-23 08:31:49,837346,1013010,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53886 42.08995),0.153646,68.474515,0.080833,0 days 00:00:13,13.0,conventional,New Flyer 40 conventional,26000.0,0.413014

In [25]:
zeros = df_final[df_final['Energy'] == 0]
zeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,Energy
0,112024,112024,0,2022-04-04 06:43:24,0,112564,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.6295 42.33369),0.000000,0.000000,0.000000,0,0.0,conventional,0,26900.0,0.0
1,112500,112500,1,2022-04-04 06:51:27,1,109326,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.627342,0.000000,0.000000,0 days 00:08:03,483.0,conventional,0,26900.0,0.0
2,112501,112501,2,2022-04-04 06:51:27,2,112565,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.0
16,114379,114379,16,2022-04-04 07:20:47,16,109340,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.57411 42.25425),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,0,26900.0,0.0
32,116181,116181,33,2022-04-04 07:52:30,33,109357,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63755 42.31962),0.000000,0.000000,0.000000,0 days 00:09:45,585.0,conventional,0,26900.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837214,1003265,1003265,837215,2022-04-23 07:00:39,837215,1012774,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.59458 42.10609),0.000000,0.000000,0.000000,0 days 00:09:53,593.0,conventional,New Flyer 40 conventional,26000.0,0.0
837215,1003266,1003266,837214,2022-04-23 07:00:39,837214,1012731,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.59458 42.10609),0.143646,1.403421,-0.006186,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
837254,1003916,1003916,837254,2022-04-23 07:24:22,837254,1012874,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.57859 42.17426),0.000000,0.000000,0.000000,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0
837329,1005901,1005901,837330,2022-04-23 08:20:51,837330,1012994,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.50799 42.08599),0.000000,0.000000,0.000000,0 days 00:01:10,70.0,conventional,New Flyer 40 conventional,26000.0,0.0
837330,1005902,1005902,837329,2022-04-23 08:20:51,837329,1012993,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.50799 42.08599),0.219882,18.198768,0.041536,0 days 00:00:00,0.0,conventional,New Flyer 40 conventional,26000.0,0.0

In [26]:
nonzeros = df_final[df_final['Energy'] != 0]
nonzeros

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,ServiceDateTime,Unnamed: 0,Unnamed: 0.1,DateKey,CalendarDate,Year,Month,...,geometry,dist,Speed,Acceleration,time_delta,time_delta_in_seconds,Powertrain,VehicleModel,Vehicle_mass,Energy
3,112584,112584,3,2022-04-04 06:52:52,3,109327,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.63305 42.3177),0.313431,21.363553,0.069816,0 days 00:01:25,85.0,conventional,0,26900.0,0.635820
4,112675,112675,4,2022-04-04 06:54:33,4,109328,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62706 42.32163),0.421734,24.191762,0.007778,0 days 00:01:41,101.0,conventional,0,26900.0,0.521954
5,112735,112735,5,2022-04-04 06:55:38,5,109329,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.62412 42.32895),0.253127,22.561887,-0.006965,0 days 00:01:05,65.0,conventional,0,26900.0,0.000713
6,112821,112821,6,2022-04-04 06:56:59,6,109330,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.61961 42.33479),0.334105,23.897266,0.004579,0 days 00:01:21,81.0,conventional,0,26900.0,0.398505
7,112913,112913,7,2022-04-04 06:58:25,7,109331,8763,2022-04-04 00:00:00.000,2022,4,...,POINT (-72.60588 42.33741),0.950194,64.012387,0.129571,0 days 00:01:26,86.0,conventional,0,26900.0,3.136412
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
837342,1006217,1006217,837342,2022-04-23 08:30:25,837342,1013006,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52768 42.09206),0.063676,52.701729,-0.148894,0 days 00:00:07,7.0,conventional,New Flyer 40 conventional,26000.0,-0.024423
837343,1006225,1006225,837343,2022-04-23 08:30:37,837343,1013007,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.52919 42.09177),0.104504,50.454912,-0.052010,0 days 00:00:12,12.0,conventional,New Flyer 40 conventional,26000.0,0.034416
837344,1006253,1006253,837344,2022-04-23 08:31:14,837344,1013008,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53309 42.09103),0.269901,42.262309,-0.061506,0 days 00:00:37,37.0,conventional,New Flyer 40 conventional,26000.0,0.070101
837345,1006262,1006262,837345,2022-04-23 08:31:36,837345,1013009,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53664 42.09038),0.245652,64.691529,0.283198,0 days 00:00:22,22.0,conventional,New Flyer 40 conventional,26000.0,1.293329
837346,1006269,1006269,837346,2022-04-23 08:31:49,837346,1013010,8782,2022-04-23 00:00:00.000,2022,4,...,POINT (-72.53886 42.08995),0.153646,68.474515,0.080833,0 days 00:00:13,13.0,conventional,New Flyer 40 conventional,26000.0,0.413014

In [27]:
df_final.to_csv(r'../../results/computed-fuel-rates.csv')

In [28]:
df_final['Energy']

0         0.000000
1         0.000000
2         0.000000
3         0.635820
4         0.521954
            ...
837342   -0.024423
837343    0.034416
837344    0.070101
837345    1.293329
837346    0.413014
Name: Energy, Length: 837347, dtype: float64

In [29]:
df_final['Energy'].dtypes

dtype('float64')